### ISSUE TITLE
Extend contribution type information within docs

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#134]
Out of a recent discussion with @Zia- we found out that the descriptions regarding the contribution type within our docs are a bit insufficient. Here is an example explanation about valuable info that is partially missing:

a) if a new feature gets created OR moved into your requested area of interest OR is now fitting to your defined filter parameter it should have the `"@creation":"true"` parameter
b) if a feature gets deleted OR moved outside of your requested area of interest OR is not fitting anymore to your defined filter parameter it should have the `"@deletion":"true"` parameter
c) if the geometry of a feature is modified, it gets the `"@geometryChange":"true"` parameter

**Comment by FabiKo117** [comment]
Additional info regarding geometry changes:

 a geometryChange for on osm-way can happen when
- a certain tag changed (e.g. highway=yes to building=yes)
- the order or member get deleted/added
- a member (node) moved/deleted

for an osm-relation geometry change can happen when
- a certain tag changed
- the order of the members (also del/add)
- a member geometry changed, see osme-way geometry change

**Comment by tyrasd** [comment]
I could imagine that the _additional info regarding geometry changes_ could be confusing if a user isn't super proficient about the OSM data modes. Also, for example, the _order of members_ is not actually what determines if a contribution is a geometry change or not. When, for example an outer way member of a multipolygon relation is split into two parts, but otherwise left unchanged including its node coordinates, there would be a change of the member list of the multipolygon relation (i.e. an _addition_ of a new outer way and a _member geometry changed_), but (the OSHDB and) the ohsome API would not report this as a contribution with `"@geometryChange" : true`, since the geometry of the resulting (multi)polygon feature stayed the same during this operation.

> c) if the geometry of a feature is modified, it gets the "@geometryChange":"true" parameter

IMHO, think this definition is short, comprehensive and sufficient.
