### ISSUE TITLE
Add property 'contributionTypes' to 'properties' parameter

### ISSUE THREAD

**Issue by FabiKo117** [GIScience/ohsome-api#136]
Currently, the `@contributionType` field gets added to the response features of the `/contributions/{geometryType}` endpoints if the `properties=metadata` parameter is given in the request. However, as it is not directly related to the other fields that get added via setting this parameter, it would be better to have it as a distinct value of the `properties` parameter, so that it gets added via setting `properties=contributionTypes` (or alternatively `contribution types`). This property should only be allowed for the `/contributions/{geometryType}` endpoint.

**Comment by tyrasd** [comment]
I changed this to milestone `1.5` since the current solution is not very good: It intermingles two different output options: OSM metadata and the contribution type. For backwards compatibility we probably have to stick with the side effect of _metadata_ enabling the _contribution type_ output. I 2.0 we can think about deprecating it, so that metadata only returns metadata :)
