### ISSUE TITLE
 getMetadataTest sometimes fails

### ISSUE THREAD

**Issue by tyrasd** [GIScience/ohsome-api#175]
### Bug Description
see https://github.com/GIScience/ohsome-api-dockerized/pull/29#issuecomment-820463344: sometimes, ` getMetadataTest` fails inexplicably. The bug happens reliably on some computers, but on other machines it never(?) happens. :shrug: 

### General Information

 - Version of the ohsome API: master, 1.4.1, etc?
 - local instance using H2 test data file
 - affects unit tests

### Expected Behaviour
The test should not fail.

**Comment by joker234** [comment]
Additional Information: Probably this is due to [ExtractMetadata.java:17](http://github.com/GIScience/ohsome-api/blob/b8f662f59ea24eaf2f5f682dbece6c9fd1053354/src/main/lombok/org/heigit/ohsome/ohsomeapi/oshdb/ExtractMetadata.java#L17-L17) being called before [Application.preRun(…)](http://github.com/GIScience/ohsome-api/blob/b8f662f59ea24eaf2f5f682dbece6c9fd1053354/src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java#L60-L60) could be called in some setups.

Until now, this error only occurred using maven commands, on older Ubuntu (based) machines.

**Comment by rtroilo** [comment]
> * Probably this is due to [ExtractMetadata.java:17](https://github.com/GIScience/ohsome-api/blob/b8f662f59ea24eaf2f5f682dbece6c9fd1053354/src/main/lombok/org/heigit/ohsome/ohsomeapi/oshdb/ExtractMetadata.java#L17-L17) being called/initialized before [Application.preRun(…)](https://github.com/GIScience/ohsome-api/blob/b8f662f59ea24eaf2f5f682dbece6c9fd1053354/src/main/lombok/org/heigit/ohsome/ohsomeapi/Application.java#L60-L60) was processed, in some setups.

I think that's the cause!, because the attribution which is loaded from the database and tested before the timeout is correctly returned.
Btw. we should change this preRun logic anyway and use more spring style configuration.

**Comment by joker234** [comment]
> Btw. we should change this preRun logic anyway and use more spring style configuration.
I would agree with that.

We should search for other potential occurrences as well.
