### ISSUE TITLE
Make list parameters seperation character consistent

### ISSUE THREAD

**Issue by SlowMo24** [GIScience/ohsome-api#295]
### Use Case Description

Some parameters can be provided as list e.g. `bbox` or `timestamp` to specify multiple values. Yet they have different formats. `bbox` uses '|' to separate two items and ',' to separate two parameters in an item while `timestamp` & co use ','  to separate items.

This causes code like https://github.com/GIScience/ohsome-py/blob/update-dependencies/ohsome/helper.py#L121 and https://github.com/GIScience/ohsome-py/blob/update-dependencies/ohsome/helper.py#L171

### Request Description

Use ';', '|' or ',' as item separator.

//cc @redfrexx

**Comment by tyrasd** [comment]
* `;` would be problematic for `groupByValues`, as it is somewhat common in tag values, contrary to `,`
* using `,` everywhere as the top-level separator would require changing the coordinate separator to something else (perhaps just space ` ` could work), but that would make copy-pasting bboxes from other tools harder and less intuitive. And FWIW `,` also has a special meaning when using GeoJSON in `bpolys`
* `|` everywhere would feel quite uncommon and cumbersome to use in many places. We only used it for the boundary parameters because we couldn't use the `,` there. Also, for the boundary parameters, most of the time one only specifies a single boundary, where the delimiter does not matter

I don't see the problem to be honest. The format is well enough [documented](https://docs.ohsome.org/ohsome-api/v1/boundaries.html). For wrapper libraries it's also not a big deal, is it?
