### ISSUE TITLE
invalid osm-type parameter doesn't always trigger an exception

### ISSUE THREAD

**Issue by tyrasd** [GIScience/ohsome-api#8]
this query fails as expected:

```
https://api.ohsome.org/v1/elements/count?bboxes=8.68132,49.41467,8.68177,49.41499&types=BLA,node
```

the same query with reversed order of the `types` value list doesn't:

```
https://api.ohsome.org/v1/elements/count?bboxes=8.68132,49.41467,8.68177,49.41499&types=node,BLA
```

AFAICT, the second query falls back to query `node`s and `relation`s in this case. Instead, it should return an HTTP 4xx error code with the same error message as the first query.

**Comment by FabiKo117** [comment]
Thanks for reporting that issue. Surprises me that I did not stumble across that in the past when I was testing the different valid input values together with invalid ones.

As the _types_ parameter, together with _keys_ and _values_ are already marked as deprecated, I mark this issue as "wontfix" as this parameter won't be available anymore in future anyway and the request triggers the expected behavior when using the _filter_ parameter.

```
https://api.ohsome.org/v1/elements/count?bboxes=8.68132,49.41467,8.68177,49.41499&filter=type:node and type:bla
```
